### ISSUE TITLE
Cannot start a docker container

### ISSUE THREAD

**Issue by BucFringe** [screepers/screeps-launcher#24]
Hi all just tried to start a screeps server in docker using both docker compose and just a strait docker image and got the same error both times. I have tried to google it but cant find anything solid any idea's.

`2021/08/09 16:10:27 screeps-launcher  ()
2021/08/09 16:10:27 Loaded config from config.yaml
2021/08/09 16:10:27 Writing package.json
2021/08/09 16:10:27 Running yarn
2021/08/09 16:10:27 Exec: yarn config set nodeLinker node-modules
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /screeps/.yarn/releases/yarn-berry.cjs:289:2658
    at Object.<anonymous> (/screeps/.yarn/releases/yarn-berry.cjs:586:2636)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2021/08/09 16:10:28 exit status 1`

any help will be great thanks.

**Comment by ags131** [comment]
This has been fixed as of today's build, by bumping node to v12. Either
update your docker image or add `nodeVersion: Erbium` to your `config.yml`
