### ISSUE TITLE
Docker install fail at yarn semver version

### ISSUE THREAD

**Issue by jsProj** [screepers/screeps-launcher#43]
I get this error when doing a fresh install using docker on windows:
```
2023/11/16 17:03:23 yarn-v1.22.21
2023/11/16 17:03:23 Exec: yarn set version berry
➤ YN0000: Retrieving https://repo.yarnpkg.com/4.0.2/packages/yarnpkg-cli/bin/yarn.js
➤ YN0001: Error: Invalid semver version. yarn --version returned:

    at /screeps/.yarn/releases/yarn-stable-temp.cjs:485:7900
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async $t.mktempPromise (/screeps/.yarn/releases/yarn-stable-temp.cjs:314:69436)
    at async eO (/screeps/.yarn/releases/yarn-stable-temp.cjs:485:7635)
    at async /screeps/.yarn/releases/yarn-stable-temp.cjs:485:4958
    at async Function.start (/screeps/.yarn/releases/yarn-stable-temp.cjs:409:2384)
    at async mu.execute (/screeps/.yarn/releases/yarn-stable-temp.cjs:485:4609)
    at async mu.validateAndExecute (/screeps/.yarn/releases/yarn-stable-temp.cjs:345:664)
    at async Gn.run (/screeps/.yarn/releases/yarn-stable-temp.cjs:359:2057)
➤ YN0000: Failed with errors in 2s 100ms
2023/11/16 17:03:28 exit status 1
```

**Comment by philipp-horstenkamp** [comment]
I have the same problem when installing via docker on an raspberrypi 64bit. When restarting tough it passes.

**Comment by martydingo** [comment]
I also have the same issue. Running `screeps-launcher` within the container the first time will result in a semvar error, simply re-running `screeps-launcher` resolves the issue.

**Comment by martydingo** [comment]
It should be handled gracefully, this currently causes a CrashBackoffLoop on my kubernetes cluster.

**Comment by martydingo** [comment]
I should add that I get past this issue but I still encounter issues regarding '@screeps/core'
